#pragma once

#define GLOBAL_COOLDOWN 2
#define BOT_REACT_DELAY 1

#define BOTLOOT_DISTANCE 20.0f
#define LOW_HEALTH_PERCENT 40
#define SPELL_DISTANCE 25.0f
#define BOT_REACT_DISTANCE 120.0f
#define BOT_GRIND_DISTANCE 60.0f
